spring:
  main:
    banner-mode: off
  application:
    name: api-service-postportalservice
  flyway:
    enabled: true
  cache:
    cache-names: portalPersonDataCache
    caffeine:
      spec: maximumSize=500, expireAfterWrite=600s
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE.URL}
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
  security:
    oauth2:
      client:
        registration:
          citizen:
            authorization-grant-type: client_credentials
            provider: citizen
          digitalregisteredletter:
            authorization-grant-type: client_credentials
            provider: digitalregisteredletter
          messagingsettings:
            authorization-grant-type: client_credentials
            provider: messagingsettings
          messaging:
            authorization-grant-type: client_credentials
            provider: messaging
          employee:
            authorization-grant-type: client_credentials
            provider: employee
openapi:
  title: Postportalservice
  name: postportalservice
  version: '@project.version@'

resilience4j:
  circuitbreaker:
    instances:
      messagingsettings:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      employee:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      messaging:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
