spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///
  security:
    oauth2:
      client:
        provider:
          digitalregisteredletter:
            token-uri: http://token.url
          messagingsettings:
            token-uri: http://token.url
          messaging:
            token-uri: http://token.url
        registration:
          digitalregisteredletter:
            client-id: the-client-id
            client-secret: the-client-secret
          messagingsettings:
            client-id: the-client-id
            client-secret: the-client-secret
          messaging:
            client-id: the-client-id
            client-secret: the-client-secret
integration:
  digitalregisteredletter:
    url: http://digitalregisteredletter.com
    connect-timeout: 10
    read-timeout: 20
  messagingsettings:
    url: http://messagingsettings.api
    connect-timeout: 10
    read-timeout: 20
  messaging:
    url: http://messaging.api
    connect-timeout: 10
    read-timeout: 20
